storage: ./storage/cache

auth:
  htpasswd:
    file: ./storage/htpasswd
web:
  title: Sinopia
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    allow_access: $all
    allow_publish: $all
  '*':
    allow_access: $all
    allow_publish: $all
    proxy: npmjs

listen: 0.0.0.0:4873

logs:
  - {type: stdout, format: pretty, level: http}

max_body_size: 30mb
